version: '3'
services:
  mailcatcher:
    restart: on-failure
    build: ./mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    container_name: mailcatcher
  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/tmp
    ports:
      - "5432:5432"
    container_name: cards_db
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=whatever-secret-key
    build: 
      context: ./cards-server-app
    command: [ "./start.sh" ]
    volumes:
      - ./cards-server-app:/usr/src/app
    ports:
      - "8000:8000"
    container_name: cards_web
    depends_on:
      - db
      - mailcatcher
